#!/usr/bin/env node
// Writes THIRD-PARTY-NOTICES.md for every production dependency (the package.json
// "dependencies" tree, followed recursively through node_modules) and exits 1 if any of
// them is not under an allow-listed licence (GPL/AGPL/LGPL/MPL/unknown stop the build).
//
// Usage: node scripts/licenses.js [--root <project dir>] [--out <file>]
//   --root defaults to the repository; --out defaults to <root>/THIRD-PARTY-NOTICES.md.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ALLOWED = new Set(['MIT', 'Apache-2.0', 'BSD-2-Clause', 'BSD-3-Clause', 'ISC', '0BSD', 'OFL-1.1', 'Unlicense', 'CC0-1.0', 'BlueOak-1.0.0',
  // Zlib: permissive (OSI-approved). Added for pako ("MIT AND Zlib"), which pdf-lib bundles.
  'Zlib']);

const args = process.argv.slice(2);
const opt = (name) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : undefined; };
const root = resolve(opt('--root') ?? join(dirname(fileURLToPath(import.meta.url)), '..'));
const outFile = resolve(opt('--out') ?? join(root, 'THIRD-PARTY-NOTICES.md'));

const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));

// Node resolution: look in <from>/node_modules, then each parent's node_modules up to root.
function findPackage(name, fromDir) {
  let dir = fromDir;
  for (;;) {
    const candidate = join(dir, 'node_modules', name);
    if (existsSync(join(candidate, 'package.json'))) return candidate;
    if (dir === root || dirname(dir) === dir) return null;
    dir = dirname(dir);
  }
}

function licenceId(pkg) {
  let l = pkg.license ?? pkg.licenses;
  if (Array.isArray(l)) l = l.map((x) => (typeof x === 'string' ? x : x?.type)).join(' OR ');
  else if (l && typeof l === 'object') l = l.type;
  return typeof l === 'string' && l.trim() ? l.trim() : 'UNKNOWN';
}

// "(MIT OR GPL-3.0)" is acceptable if one alternative is allowed; "A AND B" needs both.
function isAllowed(expr) {
  const e = expr.replace(/[()]/g, ' ').trim();
  if (/\sOR\s/.test(e)) return e.split(/\s+OR\s+/).some(isAllowed);
  if (/\sAND\s/.test(e)) return e.split(/\s+AND\s+/).every(isAllowed);
  return ALLOWED.has(e);
}

function licenceText(dir) {
  const file = readdirSync(dir).find((f) => /^(licen[sc]e|copying)(\..*)?$/i.test(f));
  return file ? { file, text: readFileSync(join(dir, file), 'utf8').trim() } : null;
}

const rootPkg = readJson(join(root, 'package.json'));
const seen = new Map(); // dir -> record
const queue = Object.keys(rootPkg.dependencies ?? {}).map((name) => ({ name, from: root, via: rootPkg.name }));
const missing = [];
while (queue.length) {
  const { name, from, via } = queue.shift();
  const dir = findPackage(name, from);
  if (!dir) { missing.push(`${name} (required by ${via})`); continue; }
  if (seen.has(dir)) continue;
  const pkg = readJson(join(dir, 'package.json'));
  const id = licenceId(pkg);
  seen.set(dir, { name: pkg.name ?? name, version: pkg.version ?? '?', licence: id, allowed: isAllowed(id), lic: licenceText(dir), repo: pkg.repository?.url ?? pkg.repository ?? pkg.homepage ?? '' });
  for (const dep of Object.keys(pkg.dependencies ?? {})) queue.push({ name: dep, from: dir, via: pkg.name });
}

const records = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
const lines = [
  '# Third-party notices',
  '',
  `ASH PDF Studio ${rootPkg.version} includes the open-source packages below. This file is generated by`,
  '`npm run licenses` (scripts/licenses.js) from the production dependency tree; do not edit it by hand.',
  '',
  '**Electron and Chromium.** The Windows builds also contain the Electron runtime (MIT, Copyright (c)',
  'Electron contributors and GitHub Inc.) and Chromium, which bundles many third-party components under',
  'their own licences. Their full notices ship next to the executable as `LICENSE.electron.txt` and',
  '`LICENSES.chromium.html` (added by electron-builder from the Electron distribution).',
  '',
  '| Package | Version | Licence |',
  '| --- | --- | --- |',
  ...records.map((r) => `| ${r.name} | ${r.version} | ${r.licence} |`),
  '',
];
for (const r of records) {
  lines.push(`## ${r.name} ${r.version}`, '', `Licence: ${r.licence}${r.repo ? `  \nSource: ${String(r.repo).replace(/^git\+/, '')}` : ''}`, '');
  if (r.lic) lines.push(`From \`${r.lic.file}\`:`, '', '```text', r.lic.text, '```', '');
  else lines.push(`The package does not ship a licence file; its package.json declares \`${r.licence}\`. The standard text of that licence applies.`, '');
}
writeFileSync(outFile, lines.join('\n'));

const bad = records.filter((r) => !r.allowed);
console.log(`licenses: ${records.length} production packages -> ${outFile}`);
for (const r of records) console.log(`  ${r.allowed ? 'ok ' : 'BAD'} ${r.name}@${r.version} ${r.licence}`);
if (missing.length) console.error(`licenses: not installed: ${missing.join(', ')} — run npm ci`);
if (bad.length || missing.length) {
  if (bad.length) console.error(`licenses: FAIL — not in allow-list [${[...ALLOWED].join(', ')}]: ${bad.map((r) => `${r.name}@${r.version} (${r.licence})`).join(', ')}`);
  process.exit(1);
}
